version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
  - cmd: dotnet tool install -g dotnet-sonarscanner
  - cmd: dotnet tool install -g coverlet.console
install:
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet publish %mainProject%
after_build:
clone_depth: 1
test_script:
  - cmd: dotnet-sonarscanner begin /k:"sonar-cloud" /d:sonar.organization="wk-j-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="940f6517a5a823b166a31a9173557dedbdbc9401" /d:sonar.cs.opencover.reportsPaths="tests/SonarCloud.Tests/coverage.opencover.xml"
  - cmd: dotnet test %testProject% /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: dotnet-sonarscanner end /d:sonar.login="940f6517a5a823b166a31a9173557dedbdbc9401"
on_finish :
deploy: off

environment:
  testProject: tests/SonarCloud.Tests/SonarCloud.Tests.csproj
  mainProject: src/SonarCloud/SonarCloud.csproj